In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import igraph as ig
import numpy as np
import os

In [ ]:
#Load the meetings dataset
calls_df = pd.read_csv('../data/raw/Montagna_Phone_Calls_Edgelist.csv')
print(calls_df.shape)
print(calls_df.columns)
calls_df.head()

(150, 3)
Index(['Source', 'Target', 'Weight'], dtype='str')

  Source Target  Weight
0    N14   N101       2
1    N18    N19       5
2    N19    N18       6
3   N102    N18       1
4    N32    N18       1

In [5]:
# Make column names lowercase
calls_df.columns = calls_df.columns.str.lower()

In [6]:
calls_df.head()

  source target  weight
0    N14   N101       2
1    N18    N19       5
2    N19    N18       6
3   N102    N18       1
4    N32    N18       1