In [23]:
import pandas as pd
import matplotlib.pyplot as plt
import igraph as ig
import numpy as np
import os

In [24]:
#Load the meetings dataset
meetings_df = pd.read_csv('../data/Montagna_Meetings_Edgelist.csv')
print(meetings_df.shape)
print(meetings_df.columns)
meetings_df.head()

(289, 1)
Index(['Source Target Weight'], dtype='str')

  Source Target Weight
0              N0 N1 1
1              N0 N2 1
2              N1 N2 1
3              N3 N4 1
4              N3 N5 1

In [25]:
meetings_df[['Source', 'Target', 'Weight']] = meetings_df['Source Target Weight'].str.split(' ', expand=True)

# Convert 'Weight' to numeric
meetings_df['Weight'] = pd.to_numeric(meetings_df['Weight'], errors='coerce')

# Set all column names in lowercase
meetings_df.columns = meetings_df.columns.str.lower()

meetings_df.drop(columns=['source target weight'], inplace=True)
meetings_df.head()

  source target  weight
0     N0     N1       1
1     N0     N2       1
2     N1     N2       1
3     N3     N4       1
4     N3     N5       1